version: '3.2'

services:
  php:
    image: 824365639512.dkr.ecr.us-east-1.amazonaws.com/divingapp_php:latest
    command: bash -c "/wait && /usr/local/bin/entrypoint.sh"
    # volumes:
    #   - src:/var/www
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

  nginx:
    image: 824365639512.dkr.ecr.us-east-1.amazonaws.com/divingapp_nginx:latest
    ports:
      - 80:80
    # volumes:
    #   - src:/var/www
    depends_on:
      - php

  db:
    image: mysql:8.0
    env_file: ./.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_db:
